[package]
name = "vulkano-www"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
publish = false

[dependencies]
lazy_static = "1.1"
mustache = "0.9"
pulldown-cmark = "0.1"
rouille = "2.1"

[dev-dependencies]
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano" }
cgmath = "0.16"
image = "0.19"
time = "0.1.37"
