version: 2

jobs:
  test:
    working_directory: ~/tgst
    docker:
      - image: mackeyja92/rustup
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -yq sudo curl wget git file g++ cmake pkg-config bison flex unzip lib32stdc++6 lib32z1
      - checkout
      - run: cargo test

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: production
